<a href="https://colab.research.google.com/github/Rosangelafl/exercicios_python_inovacao_civica/blob/main/merge_ceap_receitaFederal_aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
DTYPE = {'cnpj': str,}

In [ ]:
df_empresas = pd.read_csv('/content/drive/MyDrive/Python para inovação civica/semana_4/2019-11-19-companies.csv.xz', 
    compression='xz', dtype=DTYPE, parse_dates=['situation_date'])

In [ ]:
df_empresas.head(3)

             cnpj  ... last_updated
0  08771105000156  ...          NaN
1  42149328000114  ...          NaN
2  01155685000108  ...          NaN

[3 rows x 43 columns]

In [ ]:
df_empresas["cnpj"] = df_empresas["cnpj"].str.replace(r'\D', '', regex=True)

In [ ]:
df_empresas.situation.unique()

array([2, 4, 8, 3, 1])

In [ ]:
tipos = {
    'txNomeParlamentar': str,
    'ideCadastro': str,
    'nuCarteiraParlamentar': str,
    'nuLegislatura': str,
    'sgUF': str,
    'sgPartido': str,
    'codLegislatura': str,
    'numSubCota': str,
    'txtDescricao': str,
    'numEspecificacaoSubCota': str,
    'txtDescricaoEspecificacao': str,
    'txtFornecedor': str,
    'txtCNPJCPF': str,
    'txtNumero': str,
    'indTipoDocumento': str,
    'datEmissao': str,
    'vlrDocumento': float,
    'vlrGlosa': str,
    'vlrLiquido': float,
    'numMes': str,
    'numAno': str,
    'numParcela': str,
    'txtPassageiro': str,
    'txtTrecho': str,
    'numLote': str,
    'numRessarcimento': str,
    'nuDeputadoId': str,
    'ideDocumento': str,
}

In [ ]:
df_ceap = pd.read_csv('/content/drive/MyDrive/Python para inovação civica/semana_3/Ano-2019.csv', sep=';',
                      encoding='utf-8', error_bad_lines=False, low_memory=True,
                      parse_dates=['datEmissao'], dtype=tipos).copy()

In [ ]:
df_ceap.head(2)

  txNomeParlamentar  ...                                       urlDocumento
0        LID.GOV-CD  ...  http://camara.leg.br/cota-parlamentar/nota-fis...
1        LID.GOV-CD  ...  http://camara.leg.br/cota-parlamentar/nota-fis...

[2 rows x 31 columns]

In [ ]:
df_ceap.columns.values

array(['txNomeParlamentar', 'cpf', 'ideCadastro', 'nuCarteiraParlamentar',
       'nuLegislatura', 'sgUF', 'sgPartido', 'codLegislatura',
       'numSubCota', 'txtDescricao', 'numEspecificacaoSubCota',
       'txtDescricaoEspecificacao', 'txtFornecedor', 'txtCNPJCPF',
       'txtNumero', 'indTipoDocumento', 'datEmissao', 'vlrDocumento',
       'vlrGlosa', 'vlrLiquido', 'numMes', 'numAno', 'numParcela',
       'txtPassageiro', 'txtTrecho', 'numLote', 'numRessarcimento',
       'vlrRestituicao', 'nuDeputadoId', 'ideDocumento', 'urlDocumento'],
      dtype=object)

In [ ]:
 df_ceap['txtCNPJCPF'] = df_ceap['txtCNPJCPF'].astype('string')

In [ ]:
# vamos trocar qualquer caracter que não seja um dígito número por '', essa operação remove os dígitos
df_ceap['txtCNPJCPF'] = df_ceap['txtCNPJCPF'].str.replace(r'\D', '', regex=True)

In [ ]:
df_final = df_ceap.merge(df_empresas, how='left',
                         left_on='txtCNPJCPF', right_on='cnpj')

In [ ]:
df_final.sample(3)

       txNomeParlamentar           cpf ideCadastro  ... type state last_updated
297258     Osires Damaso  2.784828e+10      204363  ...  NaN    TO          NaN
359057            Gurgel  8.632535e+09      204442  ...  NaN    DF          NaN
322443       Schiavinato  2.769609e+10      204399  ...  NaN    PR          NaN

[3 rows x 74 columns]

In [ ]:
#from google.colab import files
#df_final.to_csv('df_final.csv')
#files.download('df_final.csv')